name: Deploy fake_cpp_project

on:
  workflow_dispatch:
    inputs:
      gitBranch:
        description: 'The git branch to test'
        required: false
        default: 'main'
        type: string
      container_id:
        description: "The github run ID from build.yaml"
        required: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GENERATOR: Ninja


# You can use permissions to modify the default permissions granted to the GITHUB_TOKEN, adding or removing access as required, so that you only allow the minimum required access.
permissions:
  actions: none
  attestations: none
  checks: none # allows an action to create a check run
  contents: write # allows an action to create a release
  deployments: none
  id-token: none
  issues: none
  models: none
  discussions: none
  packages: write # allows an action to upload and publish packages to GitHub Packages
  pages: none
  pull-requests: write # allows an action to add a label to a pull request
  security-events: none
  statuses: none

jobs:
  deploy:
    runs-on: [self-hosted, macOS, ARM64]
    environment: production
    concurrency: production

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.inputs.gitBranch }}

    - name: Install
      run: |
        docker exec -w /project -d fake_cpp_project-container-${{ inputs.container_id }} sh -c "cmake --install build --prefix install"

    - name: Package
      run: |
        docker exec -w /project -d fake_cpp_project-container-${{ inputs.container_id }} sh -c "cpack build -G TGZ"
        docker exec -w /project -d fake_cpp_project-container-${{ inputs.container_id }} sh -c "cpack build -G ZIP"

    - name: Deploy
      uses: softprops/action-gh-release@v2
      with:
        files: |
          install/fake_cpp_project.zip
          install/fake_cpp_project.tgz

    - name: Teardown
      run:
        docker container stop fake_cpp_project-container-${{ inputs.container_id }}
        docker container rm fake_cpp_project-container-${{ inputs.container_id }}
